name: Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Jib Cache
        id: cache-jib
        uses: actions/cache@v4
        with:
          path: |
            $HOME/.cache/google-cloud-tools-java/jib
            ./target/jib-cache
          key: ${{ runner.os }}-jib

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build with Maven
        run: |
          pwd
          ./mvnw package -Pcontainer -Dgithub.token=${{secrets.GITHUB_TOKEN}}
          pwd
          ls -rlah
          echo sp
          ls -rlah $HOME
